#!/usr/bin/env ruby

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'corkscrew'

hash = ARGV[0]

corkscrew = Corkscrew::Git.new(hash)
corkscrew.open
